- hosts: all
  tasks:
    - name: Get the current date in YYYY-MM-DD format
      ansible.builtin.command: "date +%F"
      register: current_date

    - name: Ensure the date-based backup directory exists
      ansible.builtin.file:
        path: "/opt/backup/SN/{{ current_date.stdout }}"
        state: directory
        mode: '0755'
        
    - shell: "ls | wc -l"
      args:
        chdir: "/opt/backup/SN/{{ current_date.stdout }}/"
      register: count

    - set_fact:
        b: "{{ count.stdout | int + 1 }}" 

    - name: Creating Directory for Backup
      file:
        path: "/opt/backup/SN/{{ current_date.stdout }}/{{ b }}"
        state: directory
        mode: "0755"
