- hosts: all
  vars_files:
    - /root/Ansible/var.yml
  tasks:
    - name: Get the current date in YYYY-MM-DD format
      ansible.builtin.command: "date +%F"
      register: current_date

    - name: Ensure the date-based backup directory exists
      ansible.builtin.file:
        path: "/opt/backup/SN/{{ current_date.stdout }}"
        state: directory
        mode: '0755'

    - name: Ensure the Service-based backup directory exists
      ansible.builtin.file:
        path: "/opt/backup/SN/{{ current_date.stdout }}/{{ service }}"
        state: directory
        mode: '0755'    
        
    - shell: "ls | wc -l"
      args:
        chdir: "/opt/backup/SN/{{ current_date.stdout }}/{{ service }}/"
      register: count

    - set_fact:
        b: "{{ count.stdout | int + 1 }}" 

    - name: Creating Directory for Backup
      file:
        path: "/opt/backup/SN/{{ current_date.stdout }}/{{ service }}/{{ b }}"
        state: directory
        mode: "0755"
        
    - set_fact:
        global_current_date: "{{ current_date.stdout }}"
      delegate_to: localhost  
        
    - set_fact:
       service2: Management
      when: service == "ManagementServices"

    - set_fact:
       service2: Internaltrn
      when: service == "InternalTrnService"

    - set_fact:
       service2: MobifinWeb
      when: service == "MobifinWebService"

    - set_fact:
       service2: Refund
      when: service == "RefundService"  

    - set_fact:
       service2: Settlement
      when: service == "SettlementService"

    - set_fact:
       service2: Tub
      when: service == "TUBService"

    - set_fact:
       service2: Report
      when: service == "ReportService"  

    - set_fact:
       service3: SN_MFS_Mgnt.service
      when: service == "ManagementServices"

    - set_fact:
       service3: SN_MFS_InternalTrn.service
      when: service == "InternalTrnService"

    - set_fact:
       service3: SN_MFS_MW.service
      when: service == "MobifinWebService"

    - set_fact:
       service3: SN_MFS_Refund.service
      when: service == "RefundService"  

    - set_fact:
       service3: SN_MFS_Settlement.service
      when: service == "SettlementService"

    - set_fact:
       service3: SN_MFS_Tub.service
      when: service == "TUBService"

    - set_fact:
       service3: SN_MFS_Report.service
      when: service == "ReportService"  
        
    - name: Taking backup for {{ service }}.jar
      command: "mv /home/akash.banda/Wizall/{{ service2 }}/Apps/{{ service }}.jar /opt/backup/SN/{{ current_date.stdout }}/{{ service }}/{{ b }}/"
      when: service != "InternalTrnService"
      ignore_errors: yes

    - name: Taking backup for InternalTransactionService.jar
      command: "mv /home/akash.banda/Wizall/{{ service2 }}/Apps/InternalTransactionService.jar /opt/backup/SN/{{ current_date.stdout }}/{{ service }}/{{ b }}/"
      when: service == "InternalTrnService"

    - name: Taking backup for {{ service }} dependencies directory
      command: "mv /home/akash.banda/Wizall/{{ service2 }}/dependencies /opt/backup/SN/{{ current_date.stdout }}/{{ service }}/{{ b }}/"
      ignore_errors: yes
      
    - name: Depploying {{ service }}.jar on {{ service2 }} service
      copy: 
         src: "/root/Ansible/Wizall/MFS-WizallMW/{{ service }}/target/{{ service }}.jar"
         dest: "/home/akash.banda/Wizall/{{ service2 }}/Apps/"
         owner: "mobifin"
         group: "mobifin"
         mode: "0755"
      when: service != "InternalTrnService"

    - name: Depploying InternalTransactionService.jar on {{ service2 }} service
      copy: 
         src: "/root/Ansible/Wizall/MFS-WizallMW/{{ service }}/target/InternalTransactionService.jar"
         dest: "/home/akash.banda/Wizall/{{ service2 }}/Apps/"
         owner: "mobifin"
         group: "mobifin"
         mode: "0755"
      when: service == "InternalTrnService"

#    - name: Deploying {{ service }} dependencies on {{ service2 }} Service
#      copy:
#         src: "/root/Ansible/Wizall/MFS-WizallMW/{{ service }}/target/dependency-jars/"
#         dest: "/home/akash.banda/Wizall/{{ service2 }}/dependencies/"
#         owner: "mobifin"
#         group: "mobifin"
#         mode: "0755" 

#    - name: Restarting {{ service3 }} service
#      service:
#         name: "{{ service3 }}"
#         state: "restarted"   


- hosts: localhost
  tasks:
#    - name: Get the current date in YYYY-MM-DD format
#      ansible.builtin.command: "date +%F"
#      register: current_date
      
    - lineinfile:
        path: "/root/Ansible/var.yml"
        line: "- date: {{ global_current_date }}"     
         

      
