- hosts: all
  tasks:
    - name: Get the current date in YYYY-MM-DD format
      ansible.builtin.command: "date +%F"
      register: current_date

    - name: Ensure the date-based backup directory exists
      ansible.builtin.file:
        path: "/opt/backup/SN/{{ current_date.stdout }}"
        state: directory
        mode: '0755'

    - name: Creating directory under date directory
      file:
        path: "/opt/backup/SN/{{ current_date.stdout }}/1"
        state: directory
        mode: "0755"
      register: dir
        
    - name: Printing output for dir 1 created
      debug:
        msg: "{{ dir }}"

    - name: Creating Directory for Backup
      file:
        path: "/opt/backup/SN/{{ current_date.stdout }}/2"
        state: directory
        mode: "0755"
      when: dir.changed == false
