- hosts: all
  vars_files:
    - /root/Ansible/var.yml 
  tasks:
    - name: Ensure the date-based rollback directory exists
      ansible.builtin.file:
        path: "/opt/rollback/SN/{{ date }}"
        state: directory
        mode: '0755'

    - name: Ensure the service-based rollback directory exists
      ansible.builtin.file:
        path: "/opt/rollback/SN/{{ date }}/{{ service}}"
        state: directory
        mode: '0755'    

    - name: Creating rollback directory
      ansible.builtin.file:
        path: "/opt/rollback/SN/{{ date }}/{{ service}}/{{ Num }}"
        state: directory
        mode: '0755'
        
    - set_fact:
       service2: Management
      when: service == "ManagementServices"

    - set_fact:
       service2: Internaltrn
      when: service == "InternalTrnService"

    - set_fact:
       service2: MobifinWeb
      when: service == "MobifinWebService"

    - set_fact:
       service2: Refund
      when: service == "RefundService"  

    - set_fact:
       service2: Settlement
      when: service == "SettlementService"

    - set_fact:
       service2: Tub
      when: service == "TUBService"

    - set_fact:
       service2: Report
      when: service == "ReportService"  

    - set_fact:
       service3: SN_MFS_Mgnt.service
      when: service == "ManagementServices"

    - set_fact:
       service3: SN_MFS_InternalTrn.service
      when: service == "InternalTrnService"

    - set_fact:
       service3: SN_MFS_MW.service
      when: service == "MobifinWebService"

    - set_fact:
       service3: SN_MFS_Refund.service
      when: service == "RefundService"  

    - set_fact:
       service3: SN_MFS_Settlement.service
      when: service == "SettlementService"

    - set_fact:
       service3: SN_MFS_Tub.service
      when: service == "TUBService"

    - set_fact:
       service3: SN_MFS_Report.service
      when: service == "ReportService"
      
    - name: Taking rollback backup for {{ service }}.jar
      command: "mv /home/akash.banda/Wizall/{{ service2 }}/Apps/{{ service }}.jar /opt/rollback/SN/{{ date }}/{{ service }}/{{ Num }}/"
      when: service != "InternalTrnService"

    - name: Doing rollback for 
      command: "mv /opt/backup/SN/{{ date }}/{{ service }}/{{ Num }}/{{ service }}.jar /home/akash.banda/Wizall/{{ service2 }}/Apps/"
      when: service != "InternalTrnService"
    
