- hosts: all
  tasks:
    - yum:
        name: "httpd"
        state: present
    - service:
        name: "httpd"
        state: started
    - copy:
        content: "Deployment is going on for git pull"
        dest: "/var/www/html/index.html"
